### ISSUE TITLE
Possibly missing generated refpages (enums.html & more)

### ISSUE THREAD

**Issue by TSlivede** [KhronosGroup/OpenCL-Docs#246] opened 2020-03-26 14:29 UTC
Hi,
I'm not sure, if this is the correct place to ask this, but it seems that https://www.khronos.org/registry/OpenCL//sdk/2.2/docs/man/html/enums.html is unreachable (presents "404… Oops") even though it is still linked in the navigation tree on the left side under "OpenCL Runtime" -> "Enumerated Types".

The corresponding source file does still seem to [exist](https://github.com/KhronosGroup/OpenCL-Docs/blob/master/man/static/enums.txt)...

**Comment by oddhack** [comment] 2020-03-26 17:10
@outofcontrol could you attach the complete list of problem links you alluded to in email here? I'll take this, unless Ben wants it.

**Comment by outofcontrol** [comment] 2020-03-26 17:20
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/vstore_halfn.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/vstoren.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/vload_halfn.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/vload_half.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/commonMax.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/abstractDataTypes.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_map_flags.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clCreateImage2D.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_channel_type.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/atomic_flag_test_and_set_explicit.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_sampler.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_context_info.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_queue_properties.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_kernel_sub_group_info.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_device_type.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_platform_info.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/get_image_num_mip_levels.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_khr_mipmap_image_writes.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/qualifiers.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_mem_migration_flags.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clCreateImage3D.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_kernel_exec_info.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_program_info.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_program_build_info.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_command_queue_info.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_device_id.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_kernel.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_pipe_properties.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_pipe_info.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/imageFunctions.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_event.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_context_properties.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_command_queue.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_program.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_kernel_work_group_info.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cles_khr_int64.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_mem.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_device_info.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_profiling_info.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_kernel_arg_info.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_buffer_create_type.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_channel_order.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_context.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_bool.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_mem_object_type.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_platform_id.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_mem_flags.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_mem_info.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_event_info.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_kernel_info.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_image_info.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_sampler_info.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/atomic_flag_test_and_set_explicitatomic_init.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_sampler_properties.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_svm_mem_flags.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_device_partition_property.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/atomicFunctions..html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/enums.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/atomic_flag_test_and_set.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/commonMin.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/divide.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/mag.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/recip.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/vloadn.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/vloada_halfn.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/vstore_half.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/vstorea_halfn.html

**Comment by oddhack** [comment] 2020-03-27 11:32
@Tsilvede

**Comment by oddhack** [comment] 2020-03-27 11:35
@outofcontrol if there are no remaining broken links, please close this - otherwise I'd appreciate an updated list and having it assigned back to me.

**Comment by outofcontrol** [comment] 2020-03-30 13:29
There are still 21 broken links as follows:

https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cles_khr_int64.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_kernel_sub_group_info.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/imageFunctions.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_context.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_device_id.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_khr_mipmap_image_writes.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/atomic_flag_test_and_set_explicitatomic_init.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_sampler.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/get_image_num_mip_levels.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_kernel.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/atomicFunctions..html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clCreateImageWithProperties.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_queue_properties.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_platform_id.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_program.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_mem.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_pipe_properties.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_command_queue.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/qualifiers.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/cl_event.html
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/abstractDataTypes.html

**Comment by roman-orekhov** [comment] 2020-04-29 14:56
There are more problems in the docs. For example, docs for 2.0 version from reference page https://www.khronos.org/registry/cl/sdk/2.0/docs/man/xhtml/clSetKernelExecInfo.html is missing note 3 available in the [pdf for 2.0 version](https://www.khronos.org/registry/OpenCL/specs/opencl-2.0.pdf#page=219). Moreover, Specification link on the reference page points to page 214 of the pdf while the relevant spec starts at page 219. Same problem with Specification link happens to https://www.khronos.org/registry/OpenCL//sdk/2.0/docs/man/xhtml/clGetDeviceInfo.html and I believe to many more 2.0 API pages.

**Comment by oddhack** [comment] 2021-08-20 14:20
@bashbaug suggest closing as duplicate of #70.

**Closed** 2021-09-02 02:32 UTC
