### ISSUE TITLE
Possible typo in Table 5 of the OpenCL 3.0 API specification

### ISSUE THREAD

**Issue by bcalidas** [KhronosGroup/OpenCL-Docs#451] opened 2020-09-22 00:43 UTC
In Table 5. List of supported param_names by clGetDeviceInfo of the OpenCL specification, there seems to be a typo
in the section on CL_DEVICE_ATOMIC_MEMORY_CAPABILITIES. This shows up at the bottom of page 82 on my pdf of the OpenCL API spec.

This line 
  "The mandated minimum capability is:" 
looks out of place. I believe it can be completely removed.

**Comment by alycm** [comment] 2020-09-22 11:23
The 3.0.3 RC version renders the bottom of the `CL_DEVICE_ATOMIC_MEMORY_CAPABILITIES` table entry as:

![image](https://user-images.githubusercontent.com/2613275/93875598-2952aa00-fccd-11ea-8f26-86e9d088d3a3.png)

There is actually more text, it just goes off the bottom the of page (and not onto the next page).

Rendering a PDF of current `master` branch shows the expected text:

![image](https://user-images.githubusercontent.com/2613275/93875299-a7fb1780-fccc-11ea-96be-f47aba1bcb2c.png)

I have a memory of a similar table issue happening recently, though I can't remember any keywords to find the issue or PR.  So I'm not sure if we fixed this on purpose, or just fixed it by chance.

I don't really know how to catch these except for manual inspection (and it can be hard to know if something is missing or not, though this case is clear).   For the PDF a table row should not exceed one page in height, but the tools produce no warning when it happens.   Even running Asciidoctor in `-v` mode produces a lot of output, but no warning of this.

**Comment by bcalidas** [comment] 2020-09-22 15:48
Thanks for the quick response. This text makes sense.

**Comment by bashbaug** [comment] 2020-09-22 21:24
I think we can close this issue then?

FWIW, I usually know that this problem is occurring because the `optimize-pdf` step in the spec build complains about a "possibly damaged PDF".  It's not a completely intuitive error message though, and it doesn't appear to be foolproof.  I have skimmed the PDF build recently though, and I don't think there are any other table cells that extend beyond a page and hence suffer from this problem.

**Comment by alycm** [comment] 2020-09-22 21:27
Yes, the issue is already fixed, closing.

Thanks for the note on `optimize-pdf`, I'll keep an eye out for that.

**Closed by alycm** 2020-09-22 21:27 UTC
