### ISSUE TITLE
Extension `cl_khr_initialize_memory` is missing enums

### ISSUE THREAD

**Issue by SunSerega** [KhronosGroup/OpenCL-Docs#921] opened 2023-05-04 06:16 UTC
https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_Ext.html#cl_khr_initialize_memory-additions-to-chapter-4

- `CL_CONTEXT_MEMORY_INITIALIZE_LOCAL_KHR`
- `CL_CONTEXT_MEMORY_INITIALIZE_PRIVATE_KHR`

These are not defined in XML or headers.
I can't find their exact values anywhere.

**Comment by bashbaug** [comment] 2023-05-08 19:18
Thank you for your astute observations, as always!

I think this is a duplicate of #872?

Regardless, AFAIK we never assigned values for these enums, but because `cl_context_memory_initialize_khr` is a bitfield type we could probably infer that `CL_CONTEXT_MEMORY_INITIALIZE_LOCAL_KHR` is the first bit `(1 << 0)` and `CL_CONTEXT_MEMORY_INITIALIZE_PRIVATE_KHR ` is the next bit `(1 << 1)`.  Indeed this is what other code on GitHub seems to have guessed.

Unless an implementor comes forward who has implemented this extension with different enum assignments I think we should just make these enum assignments "official".

**Closed** 2023-08-22 16:01 UTC
